# Karelia Admin Toolkit profile
# Passive checks: central servers plus local customer proxy.
# Active checks: local proxy first, then central server.
ZBX_SERVER=212.109.13.41,185.90.103.203,192.168.1.53
ZBX_SERVER_ACTIVE=192.168.1.53,212.109.13.41
ZBX_HOSTNAME_ITEM=system.hostname
ZBX_TIMEOUT=30
